services:
  - type: web
    name: recipe-finder
    env: python
    plan: free
    buildCommand: ""
    startCommand: python server.py
    autoDeploy: true
    envVars:
      - key: DATA_DIR
        value: /tmp
